#!/bin/bash

selection=`cat selection.txt`
prun --site ANALY_SFU --inDS data11*physics_JetTauEtmiss.merge.NTUP_TAUMEDIUM*p741/ --outDS user.NoelDawe.data11.physics_JetTauEtmiss.merge.NTUP_TAUMEDIUM.p741.skim.v1 --exec "root-skim -s '${selection}' -o or.txt -t tau --grid %IN; root-hadd skimmed.root skimmed.*.root" --outputs skimmed.root --nFilesPerJob 10 --rootVer=5.28/00
