
HOME = index_paper.txt
BROWSER = firefox
EXT = rst

DEPS := $(filter-out $(HOME),$(wildcard ./*.$(EXT)))

default: html

$(HOME).html: $(HOME) $(DEPS)
	@rst2html.py --section-numbering --cloak-email-addresses $< $@

html: $(HOME).html

show: $(HOME).html
	@$(BROWSER) index.html &

clean:
	@rm -f $(HOME).html
